name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        # Install Neovim for integration tests
        wget -O nvim.appimage https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
        chmod +x nvim.appimage
        sudo mv nvim.appimage /usr/local/bin/nvim
    
    - name: Run tests
      run: make test
      
